USE LEAP
GO

CREATE TABLE tc_coinuif (
	cuif_id INT NOT NULL IDENTITY(1,1)
	, cuif_key VARCHAR(10) NOT NULL CONSTRAINT c_tc_coinuif_cuif_key DEFAULT ('')
	, cuif_coin VARCHAR(100) NOT NULL CONSTRAINT c_tc_coinuif_cuif_coin DEFAULT ('')
	, cuif_country VARCHAR(200) NOT NULL CONSTRAINT c_tc_coinuif_cuif_country DEFAULT ('')
	, cuif_status INT NOT NULL CONSTRAINT c_tc_coinuif_cuif_status DEFAULT (1)
	, cuif_regdate DATETIME NOT NULL CONSTRAINT c_tc_coinuif_cuif_regdate DEFAULT(GETDATE())
	, cuif_moddate DATETIME NOT NULL CONSTRAINT c_tc_coinuif_cuif_moddate DEFAULT('')
)

INSERT INTO tc_coinuif (
	cuif_key
	, cuif_coin
	, cuif_country
) VALUES 
('MXN','MEXICAN PESO','MEXICO')
, ('USD','US Dollar','UNITED STATES OF AMERICA')
, ('EUR','Euro (European Monetary Unit)','EURO ZONE')
, ('MXA','Azteca','MEXICO')
, ('MXC','Centenario','MEXICO')
, ('MXH','Hidalgo','MEXICO')
, ('MXB','1/2 Hidalgo','MEXICO')
, ('MXD','1/4 Hidalgo','MEXICO')
, ('MXE','1/5 Hidalgo','MEXICO')
, ('MXU','UDIS Gubernamentales','MEXICO')
, ('MXV','Mexican Unidad de Inversion (UDI)','MEXICO')
, ('MXZ','1 OZ Liberta','MEXICO')
, ('MXF','1/2 OZ Libertad','MEXICO')
, ('MXG','1/4 OZ Libertad','MEXICO')
, ('MXI','1/10 OZ Libertad','MEXICO')
, ('MXJ','1/20 OZ Libertad','MEXICO')
, ('USN','US Dollar (Next day)','UNITED STATES OF AMERICA')
, ('USS','US Dollar (Same day)','UNITED STATES OF AMERICA')
, ('AED','UAE Dirham','UNITED ARAB EMIRATES')
, ('AFN','Afghani','AFGHANISTAN')
, ('ALL','Lek','ALBANIA')
, ('AMD','Armenian Dram','ARMENIA')
, ('ANG','Netherlands Antillian Guilder','NETHERLANDS ANTILLES')
, ('AOA','Kwanza','ANGOLA')
, ('ARS','Argentine Peso','ARGENTINA')
, ('AUD','Australian Dollar','AUSTRALIA')
, ('AWG','Aruban Guilder','ARUBA')
, ('AZN','Azerbaijanian Manat','AZERBAIJAN')
, ('BAM','Convertible Marks','BOSNIA AND HERZEGOVINA')
, ('BBD','Barbados Dollar','BARBADOS')
, ('BDT','Taka','BANGLADESH')
, ('BGN','Bulgarian Lev','BULGARIA')
, ('BHD','Bahraini Dinar','BAHRAIN')
, ('BIF','Burundi Franc','BURUNDI')
, ('BMD','Bermudian Dollar (customarily known as Bermuda Dollar)','BERMUDA')
, ('BND','Brunei Dollar','BRUNEI DARUSSALAM')
, ('BOB','Boliviano','BOLIVIA')
, ('BRL','Brazilian Real','BRAZIL')
, ('BSD','Bahamian Dollar','BAHAMAS')
, ('BTN','Ngultrum','NGULTRUM')
, ('BWP','Pula','BOTSWANA')
, ('BYR','Belarussian Ruble','BELARUS')
, ('BZD','Belize Dollar','BELIZE')
, ('CAD','Canadian Dollar','CANADA')
, ('CDF','Congolese Franc','CONGO, THE DEMOCRATIC REPUBLIC OF')
, ('CHE','WIR Euro','European Monetary Unit')
, ('CHF','Swiss Franc','SWITZERLAND')
, ('CHW','WIR Franc','European Monetary Unit')
, ('CLF','Unidades de fomento','CHILE')
, ('CLP','Chilean Peso','CHILE')
, ('CNY','Yuan Renminbi','CHINA')
, ('COP','Colombian Peso','COLOMBIA')
, ('COU','Unidad de Valor Real','COLOMBIA')
, ('CRC','Costa Rican Colon','COSTA RICA')
, ('CUC','Peso Convertible','CUBA')
, ('CUP','Cuban Peso','CUBA')
, ('CVE','Cape Verde Escudo','CAPE VERDE')
, ('CZK','Czech Koruna','CZECH REPUBLIC')
, ('DJF','Djibouti Franc','DJIBOUTI')
, ('DKK','Danish Krone','DENMARK')
, ('DOP','Dominican Peso','DOMINICAN REPUBLIC')
, ('DZD','Algerian Dinar','ALGERIA')
, ('EEK','Kroon','ESTONIA')
, ('EGP','Egyptian Pound','EGYPT')
, ('ERN','Nakfa','ERITREA')
, ('ETB','Ethiopian Birr','ETHIOPIA')
, ('FJD','Fiji Dollar','FIJI')
, ('FKP','Falkland Islands Pound','FALKLAND ISLANDS (MALVINAS)')
, ('GBP','Pound Sterling','UNITED KINGDOM')
, ('GEL','Lari','GEORGIA')
, ('GHS','Cedi','GHANA')
, ('GIP','Gibraltar Pound','GIBRALTAR')
, ('GMD','Dalasi','GAMBIA')
, ('GNF','Guinea Franc','GUINEA')
, ('GTQ','Quetzal','GUATEMALA')
, ('GYD','Guyana Dollar','GUYANA')
, ('HKD','Hong Kong Dollar','HONG KONG')
, ('HNL','Lempira','HONDURAS')
, ('HRK','Croatian Kuna','CROATIA')
, ('HTG','Gourde','HAITI')
, ('HUF','Forint','HUNGARY')
, ('IDR','Rupiah','INDONESIA')
, ('ILS','New Israeli Sheqel','ISRAEL')
, ('INR','Indian Rupee','INDIA')
, ('IQD','Iraqi Dinar','IRAQ')
, ('IRR','Iranian Rial','IRAN, ISLAMIC REPUBLIC OF')
, ('ISK','Iceland Krona','ICELAND')
, ('JMD','Jamaican Dollar','JAMAICA')
, ('JOD','Jordanian Dinar','JORDAN')
, ('JPY','Yen','JAPAN')
, ('KES','Kenyan Shilling','KENYA')
, ('KGS','Som','KYRGYZSTAN')
, ('KHR','Riel','CAMBODIA')
, ('KMF','Comoro Franc','COMOROS')
, ('KPW','North Korean Won','KOREA, DEMOCRATIC PEOPLE´S REPUBLIC OF')
, ('KRW','Won','KOREA, REPUBLIC OF')
, ('KWD','Kuwaiti Dinar','KUWAIT')
, ('KYD','Cayman Islands Dollar','CAYMAN ISLANDS')
, ('KZT','Tenge','KAZAKHSTAN')
, ('LAK','Kip','LAO PEOPLE´S DEMOCRATIC REPUBLIC')
, ('LBP','Lebanese Pound','LEBANON')
, ('LKR','Sri Lanka Rupee','SRI LANKA')
, ('LRD','Liberian Dollar','LIBERIA')
, ('LSL','Loti','LESOTHO')
, ('LTL','Lithuanian Litas','LITHUANIA')
, ('LVL','Latvian Lats','LATVIA')
, ('LYD','Libyan Dinar','LIBYAN ARAB JAMAHIRIYA')
, ('MAD','Moroccan Dirham','MOROCCO')
, ('MDL','Moldovan Leu','MOLDOVA, REPUBLIC OF')
, ('MGA','Malagasy Ariary','MADAGASCAR')
, ('MKD','Denar','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF')
, ('MMK','Kyat','MYANMAR')
, ('MNT','Tugrik','MONGOLIA')
, ('MOP','Pataca','MACAO')
, ('MRO','Ouguiya','MAURITANIA')
, ('MUR','Mauritius Rupee','MAURITIUS')
, ('MVR','Rufiyaa','MALDIVES')
, ('MWK','Kwacha','MALAWI')
, ('MYR','Malaysian Ringgit','MALAYSIA')
, ('MZN','Metical','MOZAMBIQUE')
, ('NAD','Namibia Dollar','NAMIBIA')
, ('NGN','Naira','NIGERIA')
, ('NIO','Cordoba Oro','NICARAGUA')
, ('NOK','Norwegian Krone','NORWAY')
, ('NPR','Nepalese Rupee','NEPAL')
, ('NZD','New Zealand Dollar','NEW ZEALAND')
, ('OMR','Rial Omani','OMAN')
, ('PAB','Balboa','PANAMA')
, ('PEN','Nuevo Sol','PERU')
, ('PGK','Kina','PAPUA NEW GUINEA')
, ('PHP','Philippine Peso','PHILIPPINES')
, ('PKR','Pakistan Rupee','PAKISTAN')
, ('PLN','Zloty','POLAND')
, ('PYG','Guarani','PARAGUAY')
, ('QAR','Qatari Rial','QATAR')
, ('RON','New Leu','ROMANIA')
, ('RSD','Serbian Dinar','SERBIA')
, ('RUB','Russian Ruble','RUSSIAN FEDERATION')
, ('RWF','Rwanda Franc','RWANDA')
, ('SAR','Saudi Riyal','SAUDI ARABIA')
, ('SBD','Solomon Islands Dollar','SOLOMON ISLANDS')
, ('SCR','Seychelles Rupee','SEYCHELLES')
, ('SDG','Sudanese Pound','SUDAN')
, ('SEK','Swedish Krona','SWEDEN')
, ('SGD','Singapore Dollar','SINGAPORE')
, ('SHP','Saint Helena Pound','SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA')
, ('SLL','Leone','SIERRA LEONE')
, ('SOS','Somali Shilling','SOMALIA')
, ('SRD','Surinam Dollar','SURINAME')
, ('STD','Dobra','SÃO TOME AND PRINCIPE')
, ('SVC','El Salvador Colon','EL SALVADOR')
, ('SYP','Syrian Pound','SYRIAN ARAB REPUBLIC')
, ('SZL','Lilangeni','SWAZILAND')
, ('THB','Baht','THAILAND')
, ('TJS','Somoni','TAJIKISTAN')
, ('TMT','Manat','TURKMENISTAN')
, ('TND','Tunisian Dinar','TUNISIA')
, ('TOP','Pa´anga','TONGA')
, ('TRY','Turkish Lira','TURKEY')
, ('TTD','Trinidad and Tobago Dollar','TRINIDAD AND TOBAGO')
, ('TWD','New Taiwan Dollar','TAIWAN, PROVINCE OF CHINA')
, ('TZS','Tanzanian Shilling','TANZANIA, UNITED REPUBLIC OF')
, ('UAH','Hryvnia','UKRAINE')
, ('UGX','Uganda Shilling','UGANDA')
, ('UYI','Uruguay Peso en Unidades Indexadas','URUGUAY')
, ('UYU','Peso Uruguayo','URUGUAY')
, ('UZS','Uzbekistan Sum','UZBEKISTAN')
, ('VEF','Bolivar Fuerte','VENEZUELA')
, ('VND','Dong','VIET NAM')
, ('VUV','Vatu','VANUATU')
, ('WST','Tala','SAMOA')
, ('XAF','CFA Franc BEAC ‡','CENTRAL AFRICAN REPUBLIC')
, ('XAG','Silver','International Unit')
, ('XAU','Gold','International Unit')
, ('XBA','Bond Markets Units European Composite Unit (EURCO)','European Monetary Unit')
, ('XBB','European Monetary Unit (E.M.U.-6)','European Monetary Unit')
, ('XBC','European Unit of Account 9(E.U.A.-9)','European Monetary Unit')
, ('XBD','European Unit of Account 17(E.U.A.-17)','European Monetary Unit')
, ('XCD','East Caribbean Dollar','CARIBBEAN')
, ('XDR','SDR','INTERNATIONAL MONETARY FUND (I.M.F)')
, ('XFU','UIC-Franc','European Monetary Unit')
, ('XOF','CFA Franc BCEAO †','CENTRAL AFRICAN REPUBLIC')
, ('XPD','Palladium','International Unit')
, ('XPF','CFP Franc','FRENCH POLYNESIA')
, ('XPT','Platinum','International Unit')
, ('YER','Yemeni Rial','YEMEN')
, ('ZAR','Rand','SOUTH AFRICA')
, ('ZMK','Zambian Kwacha','ZAMBIA')
, ('ZWL','Zimbabwe Dollar','ZIMBABWE')